dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/multi-cloud
go:
  - 1.11.x
  - tip

services:
  - docker
  - docker-compose

env:
  matrix:
  - TARGET=amd64
  global:
  - secure: "IhEskTMEAsBNYTQCpDSlvDxIJK5cu1r2V"

before_install:
  - sudo apt-get update

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
  # Build OpenSDS multi-cloud contanier images
  - make docker
  - docker-compose up -d

after_success:
  # Clean OpenSDS multi-cloud built data
  - make clean
