dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/multi-cloud
go:
  - 1.13
  - tip

services:
  - docker
  - docker-compose

env:
  matrix:
  - TARGET=amd64
    GO111MODULE=on
  global:
  - secure: "IhEskTMEAsBNYTQCpDSlvDxIJK5cu1r2V"

before_install:
  - wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
  - wget -q -O- "https://download.ceph.com/keys/release.asc" | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
  - sudo apt-add-repository "deb https://download.ceph.com/debian-luminous/ xenial main"
  - sudo apt-get update && sudo apt-get install -y libradosstriper-dev librados-dev librdkafka-dev

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
  # Build OpenSDS multi-cloud container images
  - make docker
  - docker-compose up -d

script:
- go test -v github.com/opensds/multi-cloud/api/pkg/policy/ -cover
- go test -v github.com/opensds/multi-cloud/api/pkg/utils/ -cover

after_success:
  # Clean OpenSDS multi-cloud built data
  - bash <(curl -s https://codecov.io/bash) -t ebba498d-3be5-4622-b65b-8ea396497a1d
  - make clean
