dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/multi-cloud
go:
  - 1.13
  - tip
  - docker-compose up -d

script:
  - ./install/CI/coverage
  - ./install/CI/test

after_success:
  # Clean OpenSDS multi-cloud built data
  - make clean
