---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mongodb-0-service
  labels:
    run: mongodb-0-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    defacementComponent: mongodb-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mongodb-0
  labels:
    env: test
    defacementComponent: mongodb-0
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      defacementComponent: mongodb-0
  template:
    metadata:
      labels:
        defacementComponent: mongodb-0
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - mongo
             topologyKey: "kubernetes.io/hostname"
      containers:
        - image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          name: mongodb-0
          resources:
            requests:
              ephemeral-storage: "1Gi"
              cpu: "500m"
              memory: "1Gi"
            limits:
              ephemeral-storage: "2Gi"
              cpu: "700m"
              memory: "2Gi"
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "mongo"
            - name: "MONGODB_ID"
              value: "mongo-0"
          livenessProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - mongo --quiet --eval "db.getMongo()"
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: mongo-localtime
              mountPath: /etc/localtime
            - name: mongo-0-data
              mountPath: /data/db/mongo-0
      volumes:
        - name: mongo-localtime
          hostPath:
            path: /etc/localtime
        - name: mongo-0-data
          persistentVolumeClaim:
            claimName: mongo-0-pv-claim        
