# Copyright 2021 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# ---------stop all multicloud services ---------
- name: cleanup mongodb
  shell: "{{ item }}"
  become_user: "{{ k8s_user }}"
  with_items:
    - "kubectl delete svc mongodb-0-service -n soda-multi-cloud"
    - "kubectl delete svc mongodb-1-service -n soda-multi-cloud"
    - "kubectl delete svc mongodb-2-service -n soda-multi-cloud"
    - "kubectl delete deployment mongodb-0 -n soda-multi-cloud"
    - "kubectl delete deployment mongodb-1 -n soda-multi-cloud"
    - "kubectl delete deployment mongodb-2 -n soda-multi-cloud"
  ignore_errors: yes

- name: patch mongodb pvc
  vars:
    patch_param: !unsafe '{"metadata":{"finalizers": []}} '
  shell: "{{ item }}"
  become_user: "{{ k8s_user }}"
  with_items:
    - 'kubectl patch pvc mongo-0-pv-claim -p "\""{{patch_param }}"\"" --type=merge -n soda-multi-cloud'
    - 'kubectl patch pvc mongo-1-pv-claim -p "\""{{patch_param }}"\"" --type=merge -n soda-multi-cloud'
    - 'kubectl patch pvc mongo-2-pv-claim -p "\""{{patch_param }}"\"" --type=merge -n soda-multi-cloud'
  ignore_errors: yes

- name: Pause for 2 seconds
  pause: seconds=2

- name: delete mongodb pvc
  shell: "{{ item }}"
  become_user: "{{ k8s_user }}"
  with_items:
    - "kubectl delete pvc mongo-0-pv-claim -n soda-multi-cloud"
    - "kubectl delete pvc mongo-1-pv-claim -n soda-multi-cloud"
    - "kubectl delete pvc mongo-2-pv-claim -n soda-multi-cloud"
  ignore_errors: yes

- name: Pause for 2 seconds
  pause: seconds=2

- name: delete mongodb pv
  shell: "{{ item }}"
  become_user: "{{ k8s_user }}"
  with_items:
    - "kubectl delete pv mongo-0-pv-volume -n soda-multi-cloud"
    - "kubectl delete pv mongo-1-pv-volume -n soda-multi-cloud"
    - "kubectl delete pv mongo-2-pv-volume -n soda-multi-cloud"
  ignore_errors: yes


- name: Pause for 2 seconds
  pause: seconds=2

- name: delete all services in the namespace soda-multi-cloud
  shell: "kubectl delete ns soda-multi-cloud"
  register: ns_delete_result
  become_user: "{{ k8s_user }}"
  ignore_errors: yes


- name: Pause for 2 seconds
  pause: seconds=2

- name: Wait for namespace to be deleted.
  shell: "kubectl get pods --namespace soda-multi-cloud -o jsonpath='{..image}'"
  register: ns_result
  become_user: "{{ k8s_user }}"
  until: ns_delete_result.stdout != "namespace soda-multi-cloud deleted"
  retries: 10
  delay: 5

- name: Pause for 2 seconds
  pause: seconds=2


# ---------delete the multi-cloud folder in /opt/opensds-gelato ---------
- name: Clean artifact path ub /opt/opensds-gelato...
  file:
    state: absent
    path: "{{ gelato_work_dir }}/multi-cloud/"
    ignore_error: yes
  become: yes
  